name:                clean-archi-for-free
version:             0.1.0.0
github:              "githubuser/clean-archi-for-free"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/clean-archi-for-free#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- attoparsec
- bytestring
- postgresql-simple
- servant
- servant-server
- text
- transformers >= 0.4
- wai
- warp

library:
  source-dirs: src

executables:
  clean-archi-for-free-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clean-archi-for-free
    - aeson
    - attoparsec
    - bytestring
    - postgresql-simple
    - servant
    - servant-server
    - text
    - transformers >= 0.4
    - wai
    - warp

tests:
  clean-archi-for-free-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clean-archi-for-free
    - hspec
    - hspec-discover
    - QuickCheck
    - text
